# Generated by Django 4.1.3 on 2022-11-24 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0004_nivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='apoderado',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Apoderados'},
        ),
        migrations.AlterModelOptions(
            name='colegio',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Colegios'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Profesores'},
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionAcademica.nivel')),
            ],
            options={
                'verbose_name_plural': ['Cursos'],
                'db_table': 'curso',
                'ordering': ['nivel'],
            },
        ),
    ]
