# Generated by Django 4.1.3 on 2022-11-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0005_alter_alumno_options_alter_apoderado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ManyToManyField(to='gestionAcademica.curso'),
        ),
    ]
