# Generated by Django 4.1.3 on 2022-11-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0006_alumno_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('asig_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionAcademica.curso')),
            ],
            options={
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignatura',
                'ordering': ['nombre'],
            },
        ),
    ]
