# Generated by Django 4.1.3 on 2022-11-24 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0007_asignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('eva_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionAcademica.asignatura')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluacion',
                'ordering': ['nombre'],
            },
        ),
    ]
