# Generated by Django 4.1.3 on 2022-11-24 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0008_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Periodos',
                'db_table': 'periodo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('clase_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('asig', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionAcademica.asignatura')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionAcademica.periodo')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionAcademica.profesor')),
            ],
            options={
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
                'ordering': ['created_at'],
            },
        ),
    ]
