# Generated by Django 4.1.3 on 2022-11-24 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0009_periodo_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('nota_id', models.AutoField(primary_key=True, serialize=False)),
                ('nota_obtenida', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('alum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionAcademica.alumno')),
                ('eva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionAcademica.evaluacion')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionAcademica.profesor')),
            ],
            options={
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
                'ordering': ['created_at'],
            },
        ),
    ]
