# Generated by Django 4.1.3 on 2022-11-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0011_alter_curso_options_curso_annio_academico'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='annio_academico',
            field=models.DateField(default='2022-01-1'),
        ),
    ]
