# Generated by Django 4.1.3 on 2022-11-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0013_remove_profesor_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='especialidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
