# Generated by Django 4.1.3 on 2022-11-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0014_profesor_especialidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='fechanacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
