# Generated by Django 4.1.3 on 2022-11-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0019_alter_nota_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
