# Generated by Django 4.1.3 on 2022-11-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0020_alter_nota_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
