# Generated by Django 4.1.3 on 2022-11-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0021_alter_nivel_created_at_alter_nivel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_collation='utf8mb3_general_ci', default='ACTIVO', max_length=8),
        ),
    ]
