# Generated by Django 4.1.3 on 2022-12-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0026_alter_alumno_genero_alter_alumno_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], db_collation='utf8mb3_general_ci', max_length=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_collation='utf8mb3_general_ci', max_length=8),
        ),
    ]
