# Generated by Django 4.1.3 on 2022-12-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0033_alter_curso_annio_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10),
        ),
    ]
