# Generated by Django 4.1.3 on 2022-12-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0034_alter_profesor_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], db_collation='utf8mb3_general_ci', max_length=10),
        ),
    ]
