# Generated by Django 4.1.3 on 2022-12-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0035_alter_apoderado_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
