# Generated by Django 4.1.3 on 2022-12-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0036_alter_asignatura_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
