# Generated by Django 4.1.3 on 2022-12-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0038_remove_alumno_curso_alumno_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='nota_obtenida',
            new_name='nota_obtenida1',
        ),
    ]
