# Generated by Django 4.1.3 on 2022-12-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0041_rename_alum_nota_alumno_rename_eva_nota_evaluacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nota_obtenida2',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota_obtenida3',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota_obtenida4',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota_obtenida5',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota_obtenida6',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota_obtenida7',
        ),
    ]
