# Generated by Django 4.1.3 on 2022-12-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0042_remove_nota_nota_obtenida2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
