# Generated by Django 4.1.3 on 2022-12-22 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0043_nota_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAcademica.curso'),
        ),
    ]
