# Generated by Django 4.1.3 on 2022-12-22 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0044_alter_asignatura_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAcademica.asignatura'),
        ),
    ]
