# Generated by Django 4.1.3 on 2022-12-22 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0046_alter_nota_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAcademica.alumno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAcademica.profesor'),
        ),
    ]
