# Generated by Django 4.1.3 on 2022-12-22 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0047_alter_nota_alumno_alter_nota_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionAcademica.profesor'),
        ),
    ]
